# Generated by Django 4.2.3 on 2023-07-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Blog Site', max_length=255),
        ),
    ]
