# Generated by Django 4.2.3 on 2023-10-05 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0011_profile_facebook_profile_instagram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook',
            new_name='fb_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='instagram',
            new_name='instagram_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='twitter',
            new_name='twitter_url',
        ),
    ]
